project:
  type: website

website:
  title: "VERSA analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - 01-cleaning.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



